apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypodes
spec:
  selector:
    matchLabels:
      app: ahmed
  replicas: 3
  template: 
    metadata: 
      name: my-first-pod
      labels: 
        app: ahmed
    spec: 
      containers:
        - image: nginx:alpine
          name: nginx-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"

